In [1]:
import pandas as pd
import numpy as np

In [2]:


# Expanded category list
kategori_list = ["makanan", "transportasi", "keperluan pribadi", "hiburan", "kesehatan", "pendidikan", "belanja", "tagihan"]

# Create 30 rows of data with fixed categories (no random generation)
df = pd.DataFrame({
    "tanggal": [
        "2025-01-01", "2025-01-01", "2025-01-02", "2025-01-02", "2025-01-02",
        "2025-01-03", "2025-01-03", "2025-01-04", "2025-01-04", "2025-01-05",
        "2025-01-05", "2025-01-05", "2025-01-06", "2025-01-07", "2025-01-07",
        "2025-01-08", "2025-01-08", "2025-01-09", "2025-01-09", "2025-01-10",
        "2025-01-10", "2025-01-11", "2025-01-11", "2025-01-12", "2025-01-12",
        "2025-01-13", "2025-01-13", "2025-01-14", "2025-01-14", "2025-01-15"
    ],
    "jumlah": [
        12000, 15000, 60000, 33000, 50000, 35000, 40000, 37000, 38000, 39000,
        100000, 41000, 42000, 43000, 25000, 75000, 18000, 22000, 85000, 30000,
        45000, 65000, 20000, 55000, 28000, 90000, 16000, 70000, 24000, 80000
    ],
    "kategori": [
        "makanan", "makanan", "transportasi", "makanan", "keperluan pribadi",
        "makanan", "makanan", "makanan", "hiburan", "makanan",
        "transportasi", "makanan", "makanan", "makanan", "keperluan pribadi",
        "transportasi", "makanan", "makanan", "hiburan", "makanan",
        "kesehatan", "transportasi", "makanan", "belanja", "makanan",
        "pendidikan", "makanan", "tagihan", "makanan", "hiburan"
    ]
})

# Display the dataframe
print("Data pengeluaran (30 rows):")
print(df)
print(f"\nTotal rows: {len(df)}")
print(f"\nKategori yang tersedia: {sorted(df['kategori'].unique())}")
print(f"\nDistribusi kategori:")
print(df['kategori'].value_counts().sort_index())

# Save to CSV
df.to_csv("pengeluaran.csv", index=False)
print("\nData berhasil disimpan ke 'pengeluaran.csv'")

Data pengeluaran (30 rows):
       tanggal  jumlah           kategori
0   2025-01-01   12000            makanan
1   2025-01-01   15000            makanan
2   2025-01-02   60000       transportasi
3   2025-01-02   33000            makanan
4   2025-01-02   50000  keperluan pribadi
5   2025-01-03   35000            makanan
6   2025-01-03   40000            makanan
7   2025-01-04   37000            makanan
8   2025-01-04   38000            hiburan
9   2025-01-05   39000            makanan
10  2025-01-05  100000       transportasi
11  2025-01-05   41000            makanan
12  2025-01-06   42000            makanan
13  2025-01-07   43000            makanan
14  2025-01-07   25000  keperluan pribadi
15  2025-01-08   75000       transportasi
16  2025-01-08   18000            makanan
17  2025-01-09   22000            makanan
18  2025-01-09   85000            hiburan
19  2025-01-10   30000            makanan
20  2025-01-10   45000          kesehatan
21  2025-01-11   65000       transportasi
22  2025-01-11   20000            makanan
23  2025-01-12   55000            belanja
24  2025-01-12   28000            makanan
25  2025-01-13   90000         pendidikan
26  2025-01-13   16000            makanan
27  2025-01-14   70000            tagihan
28  2025-01-14   24000            makanan
29  2025-01-15   80000            hiburan

Total rows: 30

Kategori yang tersedia: ['belanja', 'hiburan', 'keperluan pribadi', 'kesehatan', 'makanan', 'pendidikan', 'tagihan', 'transportasi']

Distribusi kategori:
kategori
belanja               1
hiburan               3
keperluan pribadi     2
kesehatan             1
makanan              17
pendidikan            1
tagihan               1
transportasi          4
Name: count, dtype: int64

Data berhasil disimpan ke 'pengeluaran.csv'